### ISSUE TITLE
green bubbles in weird places

### ISSUE THREAD

**Issue by jbclements** [racket/racket#4811]
**What version of Racket are you using?**
8.11 release candidate

**What program did you run?**

To set this up you appear to need 3 files in the same directory, my apologies. I will also attach a tgz if I can, but first I'll just put the three files here. It took me probably about an hour to minimize this, ugh.

I'm just going to set this up as "steps to reproduce".

1) create the following 3 files in the same directory.

```
=== another-bad-file.rkt =====
#lang racket/base

;; common file

(require racket/system
         ;gradeserver/write-student-grade-files
         ;gradeserver/make-connection
         "bad-this-qtr.rkt"
         "bad-dropped-students.rkt"
         )


;; xxxxxfile calls generate



===== end of another-bad-file.rkt =====

===== bad-this-qtr.rkt =====
#lang typed/racket/base

;; common file

(require racket/runtime-path
         racket/match
         ;gradeserver/path-quarter
         ;gradeserver/tr-structs
         )

(define-type NNReal Nonnegative-Real)

===== end of bad-this-qtr.rkt =====

===== bad-dropped-students.rkt =====
#lang typed/racket

;(provide dropped-ids)

;; these students should be ignored. The reason we can't just delete them from
;; the database is that they probably have at least one score in the database for
;; the quarter.

(define dropped-ids : (Setof String)
  (list->set
   (map symbol->string
        '()
        #;'(amart251 smacdoug sbalemi msilin))))
===== end of bad-dropped-students.rkt =====
```
2) Start up DrRacket 8.11 release candidate (or maybe HEAD, working on trying that, want to submit this in case I run
out of time before that finishes)
3) Hover over the text "ile calls" in the comment on line 13
4) See a green circle over this text. (I claim no green circle should appear over any part of a comment, much less a fragment
of one.
5) Position the mouse over the "h" in the text "bad-this-qtr.rkt" on line 8, and move the mouse down over the "r" immediately below it in line 9. See a green circle over the letters "-dropp", superimposed on the red rectangle. I claim this green circle definitely should not be there.
6) hovering over one of these green circles, hit the right mouse button. See a menu that offers to (e.g.) rename "-dropp" for you. I claim that this menu should not be offering to rename part of a filename or part of a comment.

**What should have happened?**

See list of steps above

**If you got an error message, please include it here.**

**Please include any other relevant details**
e.g., the operating system used or how you are running the code.

macOS X Ventura 13.6 (M1)

**Comment by jbclements** [comment]
Screenshots:

<img width="467" alt="Screenshot 2023-10-31 at 9 52 10 AM" src="https://github.com/racket/racket/assets/226617/aec6745a-36c1-467b-9e2b-77ffd4b59253">
<img width="446" alt="Screenshot 2023-10-31 at 9 52 23 AM" src="https://github.com/racket/racket/assets/226617/8d29c6cf-e981-4718-bee9-3984337fefb8">

**Comment by jbclements** [comment]
I should add that this seems reliably reproducible on different machines, suggesting it's less likely to be transient editor state.

**Comment by samth** [comment]
I see this behavior on HEAD on Linux.

**Comment by jbclements** [comment]
Oh! I forgot to mention a really important thing: it appears that the location of the stray green bubble on line 13 matches the position of a hash-semicolon comment in one of the files .

**Comment by rfindler** [comment]
Looks like this doesn't happen if the required files are compiled to .zo.

**Comment by rfindler** [comment]
Okay, the problem is an old one and I think we can safely say that it shouldn't affect the release (partly because it is old and partly because we'll want time to make sure there aren't any bad consequences of whatever fix we settle on (at least from the check syntax side, there doesn't seem to be a super obvious fix)).

The problem is that, when typed racket sends over the fully expanded syntax object to check syntax, check syntax is not checking to make sure that the syntax object it gets is actually the syntax object of the file that's in the definitions window. So, when there aren't compiled .zo files, if a typed racket file is required, whatever the annotations that exist in that file are, they are treated like they exist in the file that's actually open in drracket.

It is possible for check syntax to check, on each piece of information it extracts from the syntax object, if the sources match up. But it seems like it would be better to just not process the syntax object at all in the first place. Unfortunately, I'm not sure how to do that, as the fully expanded syntax object that typed racket is supplying might not start with a source location that's in the main file (as opposed to one of the required files). 

My best idea currently is that we change the protocol for sending these syntax objects and ask typed racket to identify the file that they're coming from explicitly. At least, I think that should be possible. Then, check syntax can simply discard the ones that don't match the file that it is interested in.

Does this seem reasonable, @samth ?

**Comment by samth** [comment]
Looking at the code that generates the tooltips, it always comes with a vector whose first element is a syntax object. So Typed Racket could work with some extension of the protocol which would take a path, and it would just stuff the content of `(syntax-source stx)` there. But that seems unnecessary when DrRacket is looking at the same data and could do that itself, and seems like DrRacket ought to in order to handle broken languages anyway. 

Typed Racket doesn't have, I don't think, a way to get the "current file" in a useful way, since typechecking one file can require expanding and typechecking other files (which is how we got here in the first place).

**Comment by rfindler** [comment]
If you could arrange that syntax-source of the syntax object is the file that was expanded, then I can just check that. It occurs to me that folks that are opting into this protocol could actually ensure that. An arbitrary #%module-begin might not have that invariant but we don't have arbitrary ones!

**Comment by samth** [comment]
There are a variety of syntax objects at issue here. 

1. The early fully-expanded results. These have the right syntax source.
2. The syntax object that has the `'mouse-over-tooltips` syntax property. This is usually `#'(void)` and thus has a syntax source pointing into Typed Racket.
3. The syntax objects that appear inside the `'mouse-over-tooltips` property. These have a variety of `syntax-source` values since they describe all the fully-expanded values in the module, which can come from macro expansion and thus from anywhere. 

I think just providing tooltips for forms that have the same source as the open buffer seems reasonable but I would want to actually test it out before being sure.

**Comment by rfindler** [comment]
I'm specifically talking about the ones that TR hands over to Check Syntax for processing. Not the ones that individual macros are leaving behind or that are being put inside that one in properties.

**Comment by samth** [comment]
Right the ones that get logged for check syntax to use fall into the three categories that I listed.

**Comment by rfindler** [comment]
I'm not completely following here. For category 2, how do we know that the syntax objects have useful information in them and aren't about some required file?

**Comment by samth** [comment]
Category 2 is a placeholder syntax object that only exists because of how the tooltip property works. Nothing about the system cares about that actual syntax object; its only purpose is to have the `'mouse-over-tooltips` property with interesting syntax objects in it. 

I could certainly arrange for that `#'(void)` to have whatever syntax-source was most helpful but it wouldn't address any of the problems we're discussing.

**Comment by rfindler** [comment]
I'm sorry, @samth but I'm not getting it. When TR makes this syntax object with these properties in it, how does TR know that they are supposed to be displayed. That is, how does TR know that the properties are about the file that's actually open in DrRacket as opposed to one that got expanded because the file that's open in DrRacket requires that file (and no .zo file was available)?

**Comment by rfindler** [comment]
I've pushed [a commit to a branch in the drracket repo](https://github.com/racket/drracket/commit/2fc4fefbc4bb0db76dd3fb3f6a215aaf5dfea57d) that has the change I was mentioning if you want to give it a try.

**Comment by samth** [comment]
TR doesn't know that, at all. For each module that it expands, it logs several things for check syntax. One is the fully-expanded code of the module. (That's category 1 above.) Then it also logs a syntax object (category 2) with a property describing the types of each expression in the fully-expanded module. Each of those types is about some syntax object (category 3). Those syntax objects can be from a bunch of different files (eg, if you have `(or 1 2 3 4)` in your typed racket program, there are a bunch of different `if` expressions in the fully expanded module, and each one of those will get a type). 

At no point does Typed Racket know which module is the "real" one being expanded (I don't even think it's possible to know this in Racket currently but maybe I'm wrong there). 

My conjecture was that if DrRacket looks at the sources for the individual elements of the `'mouse-over-tooltips` property (ie not making any changes to how logging of syntax objects for online-check-syntax works at all) then that would appropriately fix the problem. But looking at the relevant code (in particular the use of `find-source-editor` on line 702 of traversals.rkt) makes it clear that already happens and so it won't fix the problem.

I think the right next step is figuring out which property and which syntax object is leading DrRacket to highlight something incorrectly.

**Comment by rfindler** [comment]
> My conjecture was that if DrRacket looks at the sources for the individual elements of the `'mouse-over-tooltips` property (ie not making any changes to how logging of syntax objects for online-check-syntax works at all) then that would appropriately fix the problem. 

This is what the change I pushed on that branch is doing and it seems to work on the example at the start of this issue. Want to try it on some other examples to see if it deletes too much.

> But looking at the relevant code (in particular the use of `find-source-editor` on line 702 of traversals.rkt) makes it clear that already happens and so it won't fix the problem.

I don't think that is doing it actually. I think that's kind of doing the opposite of what we want, IIUC!

**Comment by rfindler** [comment]
I should have pointed to [this branch](https://github.com/racket/drracket/tree/limit-check-syntax-traces) not that specific commit (I updated it just now with a change to the docs).

**Comment by samth** [comment]
That commit seems to break all tooltips, eg in 

```
#lang typed/racket/base
(+ 1 2)
```

The important case for the logging is when the overall module has a syntax error. For example, when you add `(- 'foo 'bar)` to that module, the `+` expression should still get tooltips.

**Comment by rfindler** [comment]
Are the tooltips coming in with a syntax object with the source location "typed-racket/typed-racket-lib/typed-racket/typecheck/tc-toplevel.rkt"? Is it possible for TR to use the source location of the relevant file instead of that?

**Comment by samth** [comment]
The linked commit seems to make things work right given your change. Since it should be a fine improvement regardless, I'm going to push it and then we can continue testing the DrRacket change.

**Comment by rfindler** [comment]
with both of these changes I see the types in tooltips and I don't see the green bubble on the comment.
